### ISSUE TITLE
Can't run manage.py dbr

### ISSUE THREAD

**Issue by luisGithubPeru** [maciejpolanczyk/django-business-rules#5]
Hi, i'm trying to run the example on the main page but it sends me the following errors when runing " manage.py dbr " :

- first says " Could not find the GDAL library "so I installed GDAL
- then added to project settings the GDAL_LIBRARY_PATH = 'C:\\OSGeo4W64\\bin'  and "OS Error: Can't Find the specified module " raises
- tried to load gdal .dlls manually on django/contrib/gid/gdal/libgdal.py config files but finally last error "%1 is not a valid win32 application" raises

I'm runing Python 3.5.2  for winx64

**Comment by luisGithubPeru** [comment]
Sorry, I was using Django 2.* . Changed to 1.11 and everything is working.

**Comment by maciejpolanczyk** [comment]
Hi, I fixed the problem for Django 2.*, there is new release: 1.0.2. You can use it with Django 2.*

**Comment by luisGithubPeru** [comment]
Thanks!
